# railway.toml

[build]
# Tells Nixpacks which builder to use (optional, usually auto-detected)
# builder = "nixpacks" 
# Explicitly tell Nixpacks to use pnpm for installation
installCommand = "pnpm install --frozen-lockfile"
# Explicitly set the build command for the monorepo
buildCommand = "pnpm build --filter=@formbricks/web..."

[deploy]
# Use the standalone server entry point for output: 'standalone'
startCommand = "node .next/standalone/server.js"
# Set healthcheck path and timeout (optional but recommended)
# Note: Default Next.js port is 3000, Railway injects PORT env var. `next start` respects PORT.
healthcheckPath = "/api/v1/health" 
healthcheckTimeout = 600
# Specifies restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 