# railway.toml

[build]
# Tells Nixpacks which builder to use (optional, usually auto-detected)
# builder = "nixpacks" 
# Explicitly tell Nixpacks to use pnpm for installation
installCommand = "pnpm install --frozen-lockfile"
# Explicitly set the build command for the monorepo
buildCommand = "pnpm build --filter=@formbricks/web..."

[deploy]
# Explicitly set the start command, temporarily removing migrations
startCommand = "node apps/web/server.js"
# Set healthcheck path and timeout (optional but recommended)
healthcheckPath = "/api/v1/health" 
healthcheckTimeout = 600
# Specifies restart policy
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 